"""create earthquakes table

Revision ID: 8d6246f56165
Revises: b0ddae756c56
Create Date: 2025-09-09 13:36:51.934174

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8d6246f56165'
down_revision = 'b0ddae756c56'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('earthquakes', schema=None) as batch_op:
        batch_op.alter_column('magnitude',
               existing_type=sa.FLOAT(),
               nullable=False)
        batch_op.alter_column('location',
               existing_type=sa.VARCHAR(),
               nullable=False)
        batch_op.alter_column('year',
               existing_type=sa.INTEGER(),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('earthquakes', schema=None) as batch_op:
        batch_op.alter_column('year',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('location',
               existing_type=sa.VARCHAR(),
               nullable=True)
        batch_op.alter_column('magnitude',
               existing_type=sa.FLOAT(),
               nullable=True)

    # ### end Alembic commands ###
